FROM devc-archlinux:base-devel

USER root

# specific setup (start) ======================

# specific setup (end) ======================

RUN pacman -Sy --noconfirm \
  nasm \
  iasl \
  libutil-linux \
  qemu-desktop

USER ${USER}
