FROM devc-archlinux:base-devel

USER root

# specific setup (start) ======================

# specific setup (end) ======================

USER ${USER}

# install rustup components
RUN rustup +nightly component add \
  rustc-dev \
  llvm-tools-preview \
  rust-analyzer

# install compilation targets (for no_std compilation)
RUN rustup +nightly target add thumbv7em-none-eabihf

# after starting container, use nix for installing
# - neovim
# - lazygit

# start fish shell
# ENTRYPOINT ["fish"]
