FROM devc-ubuntu2404

ARG ME=shank

USER root

# additional deps
RUN apt-get install -y \
  llvm \
  clang \
  libclang-dev \
  cmake \
  libssl-dev \
  pkg-config \
  bear \
  rustfilt

USER ${USER}

# Use scripts from C2RDataset project to install the following:
# c2rust
# laertes
# CRustS
# Concrat
# Nopcrat
# Crown

# after starting container, use nix for installing
# - neovim
# - lazygit

# start fish shell
# ENTRYPOINT ["fish"]
