services:
  afl-for-solidity:
    build: .
    hostname: devc_solidity
    tty: true
    stdin_open: true
    volumes:
      - $HOME:/host_home
      - $HOME/.ssh:/home/shank/.ssh
      - $HOME/code:/home/shank/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY:
    labels:
      no-prune:
